# documentation
[lamina]
    instance = "CS31"
    log.stdout.level = 1
    log.fileout.level = 0
    log.fileout.path = 'out/log'


# documentation
[inputs]

    # documentation
    [inputs.mqtt.local]
        host.ip = "localhost"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = false
        session.reconnect_timeout_s = 0
        # log.level = 0

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/a"
            qos = 0
            tag = "lma"

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/b"
            qos = 0
            tag = "lmb"

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/c"
            qos = 0
            tag = "lmc"

    # documentation
    [inputs.mqtt.hiveb]
        host.ip = "broker.hivemq.com"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = true
        session.reconnect_timeout_s = 2
        # log.level = 0

        [[inputs.mqtt.hiveb.subs]]
            topic = "lamina/recv/a"
            qos = 0
            tag = "rma"

    # documentation
    [inputs.http.bimbo]
        host.url = "https://httpbin.org/uuid"

        # OPTIONAL request parameters
        req.method = "GET"
        req.headers = {"accept" = "application/json"}
        req.params = {}
        req.data = ""
        req.file = ".vscode/launch.json"
        req.timeout_s = 4

        res.success = [200]
        res.content.allow_duplicates = false
        res.content.decoding = "utf-8"          # auto, raw, custom
        res.content.tag = "rha"
        res.content.max_size_bytes = 10000

        poll.rate_s = 5
        poll.variance_s = 2
        poll.max_attempt = 10

        # log.level = 0

# documentation
[outputs]

    # documentation
    [outputs.mqtt.bambo]
        host.ip = "localhost"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = false
        session.reconnect_timeout_s = 10
        # log.level = 1

        [[outputs.mqtt.bambo.pubs]]
            topic = "lamina/send/a"
            qos = 0
            retain = true
            tags = ["lma", "lmb", "lmc"]

        [[outputs.mqtt.bambo.pubs]]
            topic = "lamina/send/b"
            qos = 0
            retain = false
            tags = ["rma", "rha"]

        [[outputs.mqtt.bambo.pubs]]
            topic = "lamina/send/all"
            qos = 0
            retain = false
            tags = []


# documentation
[stream]
    inputs = ["http.bimbo", "mqtt.local", "mqtt.hiveb"]
    outputs = ["mqtt.bambo"]