[lamina]
    instance = "OS21"
    log.stdout.level = 1
    log.fileout.level = 4
    log.fileout.path = 'out/log'


[inputs]
    [inputs.mqtt.local]
        host.ip = "localhost"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = false
        session.reconnect_timeout_s = 0
        log.level = 2

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/a"
            qos = 0
            tag = "lma"

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/b"
            qos = 0
            tag = "lmb"

        [[inputs.mqtt.local.subs]]
            topic = "lamina/recv/c"
            qos = 0
            tag = "lmc"


    [inputs.mqtt.hiveb]
        host.ip = "broker.hivemq.com"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = true
        session.reconnect_timeout_s = 2
        log.level = 2

        [[inputs.mqtt.hiveb.subs]]
            topic = "lamina/recv/a"
            qos = 0
            tag = "rma"

    
    [inputs.http.pumba]
        host.url = "http://0.0.0.0:11204/status"

        # OPTIONAL request parameters
        req.method = "GET"
        req.headers = {"accept" = "application/json"}
        req.params = {}
        req.data = ""
        req.file = ".vscode/launch.json"
        req.timeout_s = 4

        res.success = [200]
        res.content.allow_duplicates = false
        res.content.decoding = "utf-8"          # auto, raw, custom
        res.content.tag = "pxs"
        res.content.max_length = 10000

        poll.rate_s = 5
        poll.variance_s = 4
        poll.max_attempt = 10

        log.level = 2


[outputs]
    [outputs.mqtt.kimon]
        host.ip = "localhost"
        host.port = 1883
        session.clean = true
        session.timeout_s = 10
        session.reconnect_on_fail = false
        session.reconnect_timeout_s = 10
        log.level = 2

        [[outputs.mqtt.kimon.pubs]]
            topic = "lamina/send/a"
            qos = 0
            retain = true
            tags = ["lma", "lmb", "lmc"]

        [[outputs.mqtt.kimon.pubs]]
            topic = "lamina/send/b"
            qos = 0
            retain = false
            tags = ["pxs"]

        [[outputs.mqtt.kimon.pubs]]
            topic = "lamina/send/all"
            qos = 0
            retain = false
            tags = []


[stream]
    inputs = ["mqtt.local", "mqtt.hiveb", "http.pumba"]
    outputs = ["mqtt.kimon"]